apiVersion: v1
kind: Secret
metadata:
  name: oidc1-client-secret
type: Opaque
data:
  xpack.security.authc.realms.oidc.oidc1.rp.client_secret: {{ .Values.oidc1.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc2-client-secret
type: Opaque
data:
  xpack.security.authc.realms.oidc.oidc2.rp.client_secret: {{ .Values.oidc1.secret | b64enc }}
